services:
  dev:
    build:
      dockerfile: Dockerfile
    image: ghcr.io/yingchaoorg/local_docs-hyperf:main
    privileged: false
    container_name: local-docs-hyperf-docs
    volumes:
      - ./docs:/usr/share/nginx/html/master
    tty: true
    ports:
      - 34805:80